### ISSUE TITLE
AttributeError: 'NodeRuntimePATH' object has no attribute 'npm_install'

### ISSUE THREAD

**Issue by johnmave126** [sublimelsp/LSP-file-watcher-chokidar#4]
https://github.com/sublimelsp/LSP-file-watcher-chokidar/blob/4c7ec15bfe1b1dae7fe669e01b9353c23bb70924/watcher.py#L211

It seems that `npm_install` has been removed in the latest release of `lsp_utils`: https://github.com/sublimelsp/lsp_utils/commit/c39a95069b16f8e42a5084d7a310c24b7565c512#diff-b1cbe00fc868c6ce91d853b91b975f7bb62536811ba7395496602d6640bc5f9dL163-L165

Initializing could throw the error in title.

**Comment by rchl** [comment]
Thanks.
Broken by last minute changes in `lsp_utils`.
Fixed with https://github.com/sublimelsp/LSP-file-watcher-chokidar/releases/tag/v1.0.2 and should be available in an hour or two.

Knowing Package Control, it might not update this dependency automatically unless some other package that relies on it gets updated. So the work around is to manually trigger `Package Control: Upgrade Package` (I think).
